spring.application.name=member-service

# Database Configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://dpg-d4q3sj15pdvs738h6kd0-a.virginia-postgres.render.com/soho_bank_demo_project?sslmode=require}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:BNPBNQfwAKdDX7Yums4s8DfLdKwoUBbG}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Client url data
service.account.host=http://localhost:8080
service.account.members=/members
