spring.application.name=member-service

# Database Configuration (eagle_qlib - Frankfurt)
spring.datasource.url=${DB_URL:jdbc:postgresql://dpg-d5pl2ichg0os739l93vg-a.frankfurt-postgres.render.com/eagle_qlib?sslmode=require}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:TD2JRiPlB6MbrosDR0iKNxGtMrdHGcID}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Client url data
service.account.host=http://localhost:8080
service.account.members=/members
