package com.ca_bank.member_service.models.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

/**
 * Data Transfer Object for initiating a money transfer.
 * Defines the contract between the frontend (React) and the backend.
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class TransferRequestDTO {
    
    /**
     * The ID of the member initiating the transfer (the sender).
     */
    private Long fromMemberId;

    /**
     * The ID of the member receiving the transfer (the recipient).
     */
    private Long toMemberId;

    /**
     * The amount of money to be transferred.
     * Use decimal values (e.g., 100.50).
     */
    private BigDecimal amount;

    /**
     * Optional note describing the purpose of the transfer.
     * Limit: 500 characters.
     */
    private String description;

    /**
     * A unique key generated by the client to prevent duplicate transfers.
     * Should be a UUID v4.
     */
    private String idempotencyKey;
}
